### ISSUE TITLE
selenium中新线程里面处理随机事件

### ISSUE THREAD

**Issue by Hunmuhe** [lixi5338619/magical_spider#1]
新开的线程里面处理滑块(因为不知道多久出现)
有没有优美的办法这个子线程怎么阻碍主线程,滑块出现了,让主线程的代码暂且不运行,除了隐式等待的时间设置过长这种方案

**Comment by lixi5338619** [comment]
刚看到消息，不好意思。
可以同步处理；也可以在主线程任务中起一个异步任务，会有任务名和任务sessionid。同时监测任务状态是否执行完毕，执行完后恢复主线程。
